#!/usr/bin/sh

# Set HDMI as SECONDARY screen with script.
#$HOME/.config/bspwm/shdmi.sh

# Set HDMI as PRIMARY screen with script.
$HOME/.config/bspwm/phdmi.sh

# Run launch script.
$HOME/.config/bspwm/hotwirenv &

# Monoscale Color Palette
# Grayscale Palette
jetblack="#0A0A0A"
obsidian="#121212"
ebony="#151515"
raven="#1B1B1B"
onyx="#222222"
graphite="#2A2A2A"
charcoal="#303030"
iron="#3C3C3C"
steel="#505050"
slate="#5A5A5A"
granite="#686868"
smoke="#757575"
mist="#8D8D8D"
ash="#A0A0A0"
silver="#C0C0C0"
snow="#F8F8F8"

# Soft/Pastel Colors
vermilion_dark="#9E3B2E"
vermilion_mid="#B44A3A"
vermilion_bright="#D16048"
amber_dark="#A67C1C"
amber_mid="#C1912E"
amber_bright="#D9A640"
chartreuse_dark="#6A7D1F"
chartreuse_mid="#85A02E"
chartreuse_bright="#9DC23B"
teal_dark="#2F6B64"
teal_mid="#3F8C7F"
teal_bright="#4EA89F"
violet_dark="#5A3D7D"
violet_mid="#7856A2"
violet_bright="#9275B7"
magenta_dark="#88345F"
magenta_mid="#A14877"
magenta_bright="#C65E92"

# Additional RYB Colors
red_dark="#8B1E1E"
red_mid="#A83030"
red_bright="#C23C3C"
orange_dark="#A34E1E"
orange_mid="#BF6530"
orange_bright="#D77C3B"
yellow_dark="#A38B1E"
yellow_mid="#C1A22E"
yellow_bright="#DDC23C"
green_dark="#276D27"
green_mid="#3E8E3E"
green_bright="#5AA55A"
blue_dark="#1E3C8B"
blue_mid="#2E56B0"
blue_bright="#3C65C2"
purple_dark="#562B7D"
purple_mid="#6E4FA2"
purple_bright="#8A5FC2"

# Colors
bspc config active_border_color $ash
bspc config normal_border_color $steel
bspc config focused_border_color $snow
bspc config presel_feedback_color $smoke

# Border config.
bspc config padding_top 20
bspc config border_width         2
bspc config window_gap           4

# Ratio/Monocle
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Focus config.
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

# Window rules.
bspc rule -a "Nm-connection-editor" state=floating follow=on
bspc rule -a "Blueman-manager" state=floating follow=on
bspc rule -a "pavucontrol" state=floating follow=on
#bspc rule -a "*:*:Picture-in-Picture" state=floating sticky=on

#bspc rule -a org.mozilla.firefox desktop='^2'
#bspc rule -a LibreWolf desktop='^2'
#bspc rule -a dev.zed.Zed desktop='^5'
bspc rule -a obsidian desktop='^6'
bspc rule -a mpv desktop='^7'
bspc rule -a Gimp-2.10 desktop='^10'
